require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1

Capybara/RSpec/PredicateMatcher:
  Exclude:
    - 'spec/models/**/*'
