require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1

# RuboCopの緩和設定
RSpec/AnyInstance:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Exclude:
    - 'spec/models/**/*'
